### ISSUE TITLE
Bahaviour of back link on posts

### ISSUE THREAD

**Issue by freiheitsnetz** [Fahrradflucht/vcp-hamburg-theme#15]
Back link should call browser back instead of linking to main page

**Comment by Fahrradflucht** [comment]
Where did you even find a page with a "back" link? AFAIK they shouldn't have one...

**Comment by freiheitsnetz** [comment]
We had a "zurück" link on calendar events when clicking on the event in the eo_calendar plugin. This should then refer back to the calendar instead of main page. triggering "browser.back" should be the desired behaviour
