### ISSUE TITLE
Page-nav

### ISSUE THREAD

**Issue by freiheitsnetz** [Fahrradflucht/vcp-hamburg-theme#24]
I think the page-nav is too small compared to the headings or the distance is too close to the heading below. Furthermore I would put more space between the items. Additionally the underline is too long in the case of a long breaking item (see Intern --> Raum- und Busnutzung)

**Comment by freiheitsnetz** [comment]
This could be same as https://github.com/Fahrradflucht/vcp-hamburg-theme/issues/19

**Comment by Fahrradflucht** [comment]
#19 is more about the user even realising that this headings are clickable tabs so this is fine.

I will look into this.

**Comment by Fahrradflucht** [comment]
Closing this since 9b90659 probably makes this obsolete doesn't it? Feel free to reopen if this isn't the case.
